players = ['Archer', 'bills', 'sachin ', 'delta', 'sas']
print(players)
print(players[0:4])
print(players[0:1])
print(players[1:3])
print(players[:3])
print(players[5:])
print(players[4:])
print(players[3:])
print(players[2:])
print(players[1:])
print(players[0:])
